### ISSUE TITLE
Error: python travis_after_all.py This is a leader HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by vfa-danhnt** [dmakhno/travis_after_all#2]
Hi everyone,
I just try with travis_after_all to deploy my project ruby on Travis.
Here is my config on travis.yml:

``` yml
env:
  matrix:
    - "NUM_GROUPS=2 GROUP=1"
    - "NUM_GROUPS=2 GROUP=2"

 script: 
  - "bundle exec parallel_test spec/ -n $NUM_GROUPS --only-group $GROUP --group-by filesize --type rspec"
after_script:
  - curl -Lo travis_after_all.py https://raw.github.com/dmakhno/travis_after_all/master/travis_after_all.py
  - python travis_after_all.py

deploy:
  provider: engineyard
 .....
```

Travis build ok untill here: 

```
$ python travis_after_all.py
 This is a leader
HTTP Error 404: Not Found
```

Have you any idea about that?
I would like after build success matrix tasks, it will be auto deploy my project.
